db_tree/db_too_tree/urls.py
from django.urls import path

from db_too_tree import views

app_name = 'db_too_tree'

urlpatterns = [
    path('<str:title>/', views.index, name='index')
]

db_tree/db_tree/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
# from django.

import db_too_tree.urls

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(db_too_tree.urls))
]
# urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

db_tree/db_too_tree/models.py
from django.db import models


class Dir(models.Model):
    title = models.CharField(max_length=100)
    parent = models.ForeignKey(
        "self",
        on_delete=models.CASCADE,
        related_name='dirs',
        null=True,
        blank=True,
        default=None
    )
    create_date = models.DateTimeField(
        auto_now_add=True
    )

    def __str__(self) -> str:
        return self.title
    
    def __repr__(self) -> str:
        return self.title
    
    # class Meta:
    #     ordering = ['-create_date']

db_tree/db_too_tree/views.py
from django.shortcuts import render


def index(request, title):
    return render(
        request,
        'index.html',
        {'title': title}
    )

db_tree/templates/index.html
<html>
    {% load template_tags %}
    {% load static %}
    <head>
        <link rel="stylesheet" href="{% static 'app.css' %}">
    </head>

    <body>
        <div class="main">
            {% draw_menu title %}
        </div>
    </body>
</html>

db_tree/templates/main_menu.html
<ul class="first">
{% for child in new %}
    <a href="{% url 'db_too_tree:index' child %}">
        {{ child }}
    </a>
    {% for children in child.dirs.all %}
        {% if children != current_dir %}
            <li class="inner">
                <a href="{% url 'db_too_tree:index' children %}">
                    {{ children }}
                </a>
            </li>
        {% endif %}
    {% endfor %}
{% endfor %}
<li>Current menu: {{ current_dir }}</li>
<ul class="first">
{% for child in current_dir.dirs.all %}
    <li class="inner">
        <a href="{% url 'db_too_tree:index' child %}">
            {{ child }}
        </a>
    </li>
{% endfor %}
</ul>
</ul>